---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubemantics-service-account
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: list-resources
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "configmaps", "persistentvolumes"]
  verbs: ["list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: list-resources-binding
subjects:
- kind: ServiceAccount
  name: kubemantics-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: list-resources
  apiGroup: rbac.authorization.k8s.io
